# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Install required packages
RUN pip install --no-cache-dir prefect && \
    pip install --no-cache-dir -r requirements.txt

# Register flows and then start Prefect agent
CMD ["sh", "-c", "python worker/prefect/register_flows.py && prefect agent start local"]