version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.pytest.app
    ports:
      - "8000:8000"
    container_name: app
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./pytest/data/test.db
    volumes:
      - ./reports:/app/pytest/reports
      - ./data:/app/pytest/data  # Ensure the SQLite file is available in this directory
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./pytest/reports/htmlcov:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - app

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    volumes:
      - ./pytest/data:/app/data  # Ensure the SQLite file is available in this directory
  

  allure:
    image: frankescobar/allure-docker-service
    ports:
      - "4040:4040"
    volumes:
      - ./pytest/reports/allure-results:/app/allure-results
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  app_postgres_data: