version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.pytest.app
    ports:
      - "8000:8000"
    container_name: app
    environment:
      TEST_DATABASE_URL: 'sqlite+aiosqlite:///:memory:'
      API_KEY_SECRET: laisjdf;asdifj[fi9wejr'wekf]
      ENCRYPTION_KEY_SECRET: alsk;fj2 i3jeqealfjansdflkmadf
    volumes:
      - ./pytest/reports:/usr/src/app/pytest/reports
      - ./pytest/data:/usr/src/app/pytest/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
