version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    container_name: app
    depends_on:
      - app-db-server
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@app-db-server:5433/dp_farm
    volumes:
      - ./reports:/app/reports
    networks:
      - app-network

  app-db-server:
    image: postgres:14
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dp_farm
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: -p 5433
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - app-db-server
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "6060:8080"
    environment:
      ADMINER_DEFAULT_SERVER: app-db-server
    depends_on:
      - app-db-server
    networks:
      - app-network
      

  nginx:
    image: nginx:alpine
    volumes:
      - ./reports/htmlcov:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  app_postgres_data: