version: '3.8'
services:
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.prefect_worker
    container_name: prefect-worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PREFECT__SERVER__HOST=${PREFECT__SERVER__HOST}
    depends_on:
      - db
      - prefect-server
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    container_name: app
    depends_on:
      - prefect-worker
      - db
      - prefect-server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PREFECT__SERVER__HOST=${PREFECT__SERVER__HOST}
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
  

  prefect-server:
    image: prefecthq/prefect-server:latest
    container_name: prefect-server
    environment:
      PREFECT_SERVER_DB_CONNECTION_URL: ${DATABASE_URL}
    ports:
      - "4200:4200"
    depends_on:
      - db
    networks:
      - app-network
  
  prefect-ui:
    image: prefecthq/ui:latest
    container_name: prefect-ui
    ports:
      - "8080:8080"
    depends_on:
      - prefect-server
    networks:
      - app-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: