version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    container_name: app
    depends_on:
      - app-db-server
    environment:
      DATABASE_URL: mssql+pyodbc://sa:password@app-db-server:1433/dp_farm?driver=ODBC+Driver+17+for+SQL+Server
    volumes:
      - .:/usr/src/app
    networks:
      - pytest-app-sqlserver-network

  app-db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    volumes:
      - farm_pytest_app_sqlserver_data:/var/opt/mssql
    networks:
      - pytest-app-sqlserver-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "6060:8080"
    environment:
      ADMINER_DEFAULT_SERVER: app-db-server
    depends_on:
      - app-db-server
    networks:
      - pytest-app-sqlserver-network

networks:
  pytest-app-sqlserver-network:
    driver: bridge

volumes:
  farm_pytest_app_sqlserver_data:

