#configuration constants
param_plant_code_list_csv_isRequired = False
calculatedIsRowLevelCustomerSecurityUsed = False
calculatedIsRowLevelOrgCustomerSecurityUsed = False
calculatedIsRowLevelOrganizationSecurityUsed = False
