#configuration constants

param_request_flavor_code_isRequired = True
param_request_other_flavor_isRequired = False
param_request_some_int_val_isRequired = True 
param_request_some_big_int_val_isRequired = True 
param_request_some_bit_val_isRequired = True  
param_request_is_edit_allowed_isRequired = False 
param_request_is_delete_allowed_isRequired = False  
param_request_some_float_val_isRequired = True 
param_request_some_decimal_val_isRequired = True 
param_request_some_utc_date_time_val_isRequired = True
param_request_some_date_val_isRequired = True
param_request_some_money_val_isRequired = True 
param_request_some_n_var_char_val_isRequired = True 
param_request_some_var_char_val_isRequired = True    
param_request_some_text_val_isRequired = True   
param_request_some_phone_number_isRequired = True 
param_request_some_email_address_isRequired = True 
param_request_sample_image_upload_file_isRequired = False
calculatedIsRowLevelCustomerSecurityUsed = False
calculatedIsRowLevelOrgCustomerSecurityUsed = False
calculatedIsRowLevelOrganizationSecurityUsed = False
