#configuration constants
param_email_isRequired = True
param_password_isRequired = True

calculatedIsRowLevelCustomerSecurityUsed = False
calculatedIsRowLevelOrgCustomerSecurityUsed = False
calculatedIsRowLevelOrganizationSecurityUsed = False