#configuration constants
param_email_isRequired = True
param_password_isRequired = True
param_confirm_password_isRequired = True
param_first_name_isRequired = True
param_last_name_isRequired = True

calculatedIsRowLevelCustomerSecurityUsed = False
calculatedIsRowLevelOrgCustomerSecurityUsed = False
calculatedIsRowLevelOrganizationSecurityUsed = False