# flows/constants/tac_register.py
"""
    configuration constants
"""
PARAM_EMAIL_IS_REQUIRED = True
PARAM_PASSWORD_IS_REQUIRED = True
PARAM_CONFIRM_PASSWORD_IS_REQUIRED = True
PARAM_FIRST_NAME_IS_REQUIRED = True
PARAM_LAST_NAME_IS_REQUIRED = True
CALCULATED_IS_ROW_LEVEL_CUSTOMER_SECURITY_USED = False
CALCULATED_IS_ROW_LEVEL_ORG_CUSTOMER_SECURITY_USED = False
CALCULATED_IS_ROW_LEVEL_ORGANIZATION_SECURITY_USED = False
