# flows/constants/tac_register_init_obj_wf.py
"""
    configuration constants
"""

CALCULATED_IS_ROW_LEVEL_CUSTOMER_SECURITY_USED = False
CALCULATED_IS_ROW_LEVEL_ORG_CUSTOMER_SECURITY_USED = False
CALCULATED_IS_ROW_LEVEL_ORGANIZATION_SECURITY_USED = False
